var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/brevo/email/route.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/[root-of-the-server]__21a63qq._.js")
R.c("server/chunks/node_modules_1ollbg3._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_next-internal_server_app_api_brevo_email_route_actions_015i1_0.js")
R.m(670665)
module.exports=R.m(670665).exports
