var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/verify/route.js")
R.c("server/chunks/[root-of-the-server]__1n8rrs0._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_0eio5uu._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_verify_route_actions_048d-5u.js")
R.m(841385)
module.exports=R.m(841385).exports
