var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/access/generate/route.js")
R.c("server/chunks/[root-of-the-server]__19gz92f._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/_0eio5uu._.js")
R.c("server/chunks/_next-internal_server_app_api_access_generate_route_actions_1nd9jbe.js")
R.m(839855)
module.exports=R.m(839855).exports
