var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/tribute-purchases/route.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__05brt_2._.js")
R.c("server/chunks/_0eio5uu._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_1ollbg3._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_tribute-purchases_route_actions_0rm3rby.js")
R.m(955144)
module.exports=R.m(955144).exports
