var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/access/list/route.js")
R.c("server/chunks/[root-of-the-server]__1x91vwn._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/_0eio5uu._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/_next-internal_server_app_api_access_list_route_actions_052e417.js")
R.m(880928)
module.exports=R.m(880928).exports
