var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/email/subscribe/route.js")
R.c("server/chunks/[root-of-the-server]__1ltpi4y._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/src_lib_email_service_ts_05jwna-._.js")
R.c("server/chunks/[root-of-the-server]__02_2sm-._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/src_lib_email-templates_ts_1292fdw._.js")
R.c("server/chunks/_next-internal_server_app_api_email_subscribe_route_actions_20k6j33.js")
R.m(710742)
module.exports=R.m(710742).exports
